name: Auto Meal Update
on:
  schedule:
    - cron: '0 22 * * *' # 每天北京时间早上 6 点运行
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Run
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: |
          pip install requests
          python update_meals.py
