name: Ducky Menu Auto-Evolve

on:
  schedule:
    - cron: '0 20 * * *' # 北京时间凌晨 4 点
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Update Script
        env:
          GH_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: "a05bf384ba10cf0c9c4f69a3f85f5a12"
          FOOD_API_KEY: ${{ secrets.FOOD_API_KEY }}
        run: |
          python update_meals.py
